apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstresssimulator-deploy
  namespace: test
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    
  replicas: 2
  
  selector:
    matchLabels:
      app: webstresssimulator
  
  template:
    metadata:
      labels:
        app: webstresssimulator
    spec:
      volumes:
      - name: cache
        hostPath:
          path: /tmp
          type: Directory
      imagePullSecrets:
      - name: docker-regcred
      containers:
      - name: webstresssimulator
        image: alinahid477/web-stress-simulator:1.0.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /web-stress-simulator-1.0.0/healthcheck
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: cache
          mountPath: /var/lib/docker
        # envFrom:
        #   - configMapRef:
        #       name: foobar-config
---
apiVersion: v1
kind: Service
metadata:
  name: webstresssimulator-service
  namespace: test
spec:
  selector:
    app: webstresssimulator
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer # ClusterIP # NodePort # 